apiVersion: apps/v1
kind: Deployment
metadata:
  name: replica-set
  labels:
    app: nft-server
    # tier: replica_set
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nft-server
  template:
    metadata:
      labels:
        app: nft-server
    spec:
      containers:
      - name: nft-server
        image: oleandertwig/nft-server:latest
        ports: 
        - containerPort: 8000